# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKt6N6RSIsYnZsny8LWZRi7JfpGJI2WY
"""

import os

from google.colab import drive
drive.mount('/content/drive')

os.chdir("/content/drive/MyDrive/海外実務訓練_Nam先生_研究")

!pip install japanize_matplotlib

!pip install scikit-image

!pip install streamlit
import streamlit as st

# タイトル
st.title("変圧器故障診断：Duval Triangle 1")

# 入力フォーム（サイドバーに配置）
st.sidebar.header("ガス濃度の入力 (ppm)")
ch4 = st.sidebar.number_input("CH₄ (メタン)", min_value=0.0, value=100.0)
c2h4 = st.sidebar.number_input("C₂H₄ (エチレン)", min_value=0.0, value=50.0)
c2h2 = st.sidebar.number_input("C₂H₂ (アセチレン)", min_value=0.0, value=10.0)

# 診断とグラフ表示のボタン
if st.button("診断を実行"):
    try:
        # ご自身の関数を実行
        # ※ plot_duval1 内の plt.show() を plt.gcf() に書き換えたものを用意
        fig = plot_duval1_streamlit(ch4, c2h4, c2h2)
        st.pyplot(fig) # Streamlitで図を表示
    except Exception as e:
        st.error(f"エラーが発生しました: {e}")



import numpy as np
import matplotlib.pyplot as plt

# --- 診断ルール (IEEE Table 6) ---
def duval1_zone(c1, c2, c3):
    if c1 >= 98: return "PD"
    if c3 < 4:
        if c2 < 20: return "T1"
        if 20 <= c2 < 50: return "T2"
        if c2 >= 50: return "T3"
    if c2 >= 50 and c3 < 15: return "T3"
    if c2 >= 23 and (c3 >= 29 or (13 <= c3 < 29 and c2 < 40)): return "D2"
    if c2 < 23 and c3 >= 13: return "D1"
    if (c2 < 50 and 4 <= c3 < 13) or (40 <= c2 < 50 and 13 <= c3 < 29) or (c2 >= 50 and 15 <= c3 < 29):
        return "DT"
    return "ND"

# --- バリセン変換 (C2H4, C2H2 -> XY) ---
def pct_to_xy(c2, c3):
    c1 = 100 - c2 - c3
    return c2/100 + c1/200, (c1/100)*np.sqrt(3)/2

# --- プロット ---
def plot_duval1(ch4, c2h4, c2h2, step=0.5):
    total = ch4 + c2h4 + c2h2
    if total <= 0: raise ValueError("ガス濃度ゼロ")
    C1, C2, C3 = [g/total*100 for g in (ch4, c2h4, c2h2)]

    # 格子生成して分類
    xs, ys, ids = [], [], []
    zones = ["PD","T1","T2","T3","D1","D2","DT","ND"]
    colors = {"PD":"#E5CCFF","T1":"#E5E5E5","T2":"#BFE6FF","T3":"#5063B0",
              "D1":"#FFD6A5","D2":"#FF6F61","DT":"#FF9F9F","ND":"#D3D3D3"}
    z2id = {z:i for i,z in enumerate(zones)}

    for c2 in np.arange(0,101,step):
        for c3 in np.arange(0,101-c2,step):
            x,y = pct_to_xy(c2,c3)
            xs.append(x); ys.append(y)
            ids.append(z2id[duval1_zone(100-c2-c3, c2, c3)])

    # グリッド化して塗り分け
    fig, ax = plt.subplots(figsize=(7,7))
    sc = ax.scatter(xs, ys, c=ids, cmap=plt.matplotlib.colors.ListedColormap([colors[z] for z in zones]), s=5, marker='s')

    # 枠
    apex = (0.5, np.sqrt(3)/2)
    ax.plot([0,1,apex[0],0],[0,0,apex[1],0],'k',lw=2)

    # 頂点ラベル
    ax.text(0.5,apex[1]+0.02,"CH₄ (100%)",ha="center")
    ax.text(-0.02,-0.02,"C₂H₂ (100%)",ha="right",va="top")
    ax.text(1.02,-0.02,"C₂H₄ (100%)",ha="left",va="top")

    # 各ゾーンのラベル（だいたいの重心）
    for z in zones:
        mask = np.array(ids)==z2id[z]
        if np.any(mask):
            xm, ym = np.mean(np.array(xs)[mask]), np.mean(np.array(ys)[mask])
            ax.text(xm, ym, z, ha="center", va="center", fontsize=9, fontweight="bold", color="black")

    # 入力点
    xp, yp = pct_to_xy(C2,C3)
    diag = duval1_zone(C1,C2,C3)
    ax.plot(xp, yp, 'ro', ms=10, mec='k')
    ax.text(0.5,-0.07,f"Diagnosis: {diag}",ha="center",va="top",bbox=dict(facecolor="white",edgecolor="k"))

    ax.set_aspect('equal'); ax.axis('off')
    ax.set_title("Duval Triangle 1 ",fontweight="bold")
    plt.tight_layout(); plt.show()

# --- 実行 ---
if __name__=="__main__":
    ch4 = float(input("CH4 ppm: "))
    c2h4 = float(input("C2H4 ppm: "))
    c2h2 = float(input("C2H2 ppm: "))
    plot_duval1(ch4,c2h4,c2h2,step=0.5)